# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cogzymes', '0001_initial'),
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='organism',
            field=models.ForeignKey(default=None, blank=True, to='cogzymes.Organism', null=True),
        ),
        migrations.AddField(
            model_name='reaction_synonym',
            name='reaction',
            field=models.ForeignKey(to='annotation.Reaction'),
        ),
        migrations.AddField(
            model_name='reaction_synonym',
            name='source',
            field=models.ForeignKey(to='annotation.Source'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='enzymes',
            field=models.ManyToManyField(to='annotation.Enzyme', through='annotation.Catalyst'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='source',
            field=models.ForeignKey(to='annotation.Source'),
        ),
        migrations.AddField(
            model_name='profunc_result',
            name='gene',
            field=models.ForeignKey(to='annotation.Gene'),
        ),
        migrations.AddField(
            model_name='profunc_result',
            name='go_term',
            field=models.ForeignKey(to='annotation.GO'),
        ),
        migrations.AddField(
            model_name='profunc_prediction2',
            name='gene',
            field=models.ForeignKey(to='annotation.Gene'),
        ),
        migrations.AddField(
            model_name='profunc_prediction2',
            name='reaction',
            field=models.ForeignKey(to='annotation.Reaction'),
        ),
        migrations.AddField(
            model_name='profunc_prediction2',
            name='result',
            field=models.ForeignKey(to='annotation.Profunc_result'),
        ),
        migrations.AddField(
            model_name='profunc_prediction',
            name='gene',
            field=models.ForeignKey(to='annotation.Gene'),
        ),
        migrations.AddField(
            model_name='profunc_prediction',
            name='go',
            field=models.ForeignKey(to='annotation.GO'),
        ),
        migrations.AddField(
            model_name='profunc_prediction',
            name='reaction',
            field=models.ForeignKey(to='annotation.Reaction'),
        ),
        migrations.AddField(
            model_name='mtg_prediction',
            name='gene',
            field=models.ForeignKey(to='annotation.Gene'),
        ),
        migrations.AddField(
            model_name='mtg_prediction',
            name='reaction',
            field=models.ForeignKey(to='annotation.Reaction'),
        ),
        migrations.AddField(
            model_name='model_reaction',
            name='db_reaction',
            field=models.ForeignKey(blank=True, to='annotation.Reaction', null=True),
        ),
        migrations.AddField(
            model_name='model_reaction',
            name='mapping',
            field=models.ManyToManyField(default=None, to='annotation.Reaction_group', null=True, through='annotation.Mapping', blank=True),
        ),
        migrations.AddField(
            model_name='model_reaction',
            name='metabolites',
            field=models.ManyToManyField(related_name='metabolites_of_reaction', to='annotation.Model_metabolite'),
        ),
        migrations.AddField(
            model_name='model_reaction',
            name='products',
            field=models.ManyToManyField(related_name='products_of_reaction', to='annotation.Model_metabolite'),
        ),
        migrations.AddField(
            model_name='model_reaction',
            name='source',
            field=models.ForeignKey(to='annotation.Source'),
        ),
        migrations.AddField(
            model_name='model_reaction',
            name='substrates',
            field=models.ManyToManyField(related_name='substrates_of_reaction', to='annotation.Model_metabolite'),
        ),
        migrations.AddField(
            model_name='model_metabolite',
            name='compartment',
            field=models.ForeignKey(to='annotation.Compartment'),
        ),
        migrations.AddField(
            model_name='model_metabolite',
            name='db_metabolite',
            field=models.ForeignKey(blank=True, to='annotation.Metabolite', null=True),
        ),
        migrations.AddField(
            model_name='model_metabolite',
            name='source',
            field=models.ForeignKey(to='annotation.Source'),
        ),
        migrations.AddField(
            model_name='metabolite_synonym',
            name='metabolite',
            field=models.ForeignKey(to='annotation.Metabolite'),
        ),
        migrations.AddField(
            model_name='metabolite_synonym',
            name='source',
            field=models.ForeignKey(to='annotation.Source'),
        ),
        migrations.AddField(
            model_name='metabolite',
            name='source',
            field=models.ForeignKey(to='annotation.Source'),
        ),
        migrations.AddField(
            model_name='metabolic_model',
            name='direction',
            field=models.ForeignKey(to='annotation.Direction'),
        ),
        migrations.AddField(
            model_name='metabolic_model',
            name='reaction',
            field=models.ForeignKey(to='annotation.Reaction'),
        ),
        migrations.AddField(
            model_name='metabolic_model',
            name='source',
            field=models.ForeignKey(to='annotation.Source'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='group',
            field=models.ForeignKey(to='annotation.Reaction_group'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='method',
            field=models.ForeignKey(to='annotation.Method'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='reaction',
            field=models.ForeignKey(related_name='reaction_mapped', to='annotation.Model_reaction'),
        ),
        migrations.AddField(
            model_name='iah991_prediction',
            name='gene',
            field=models.ForeignKey(to='annotation.Gene'),
        ),
        migrations.AddField(
            model_name='iah991_prediction',
            name='reaction',
            field=models.ForeignKey(to='annotation.Reaction'),
        ),
        migrations.AddField(
            model_name='go_reaction',
            name='ec',
            field=models.ForeignKey(to='annotation.EC'),
        ),
        migrations.AddField(
            model_name='go_reaction',
            name='go',
            field=models.ForeignKey(to='annotation.GO'),
        ),
        migrations.AddField(
            model_name='go_reaction',
            name='reaction',
            field=models.ForeignKey(to='annotation.Reaction'),
        ),
        migrations.AddField(
            model_name='go2ec',
            name='ec',
            field=models.ForeignKey(to='annotation.EC'),
        ),
        migrations.AddField(
            model_name='go2ec',
            name='go',
            field=models.ForeignKey(to='annotation.GO'),
        ),
        migrations.AddField(
            model_name='go',
            name='enzymes',
            field=models.ManyToManyField(to='annotation.Enzyme', through='annotation.Catalyst_go'),
        ),
        migrations.AddField(
            model_name='ffpred_result',
            name='gene',
            field=models.ForeignKey(to='annotation.Gene'),
        ),
        migrations.AddField(
            model_name='ffpred_result',
            name='go_term',
            field=models.ForeignKey(to='annotation.GO'),
        ),
        migrations.AddField(
            model_name='ffpred_prediction',
            name='gene',
            field=models.ForeignKey(to='annotation.Gene'),
        ),
        migrations.AddField(
            model_name='ffpred_prediction',
            name='go',
            field=models.ForeignKey(to='annotation.GO'),
        ),
        migrations.AddField(
            model_name='ffpred_prediction',
            name='reaction',
            field=models.ForeignKey(to='annotation.Reaction'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='source',
            field=models.ForeignKey(blank=True, to='annotation.Source', null=True),
        ),
        migrations.AddField(
            model_name='enzyme',
            name='genes',
            field=models.ManyToManyField(to='annotation.Gene'),
        ),
        migrations.AddField(
            model_name='enzyme',
            name='source',
            field=models.ForeignKey(to='annotation.Source'),
        ),
        migrations.AddField(
            model_name='eficaz_result',
            name='ec',
            field=models.ForeignKey(to='annotation.EC'),
        ),
        migrations.AddField(
            model_name='eficaz_result',
            name='gene',
            field=models.ForeignKey(to='annotation.Gene'),
        ),
        migrations.AddField(
            model_name='eficaz_prediction',
            name='gene',
            field=models.ForeignKey(to='annotation.Gene'),
        ),
        migrations.AddField(
            model_name='eficaz_prediction',
            name='reaction',
            field=models.ForeignKey(to='annotation.Reaction'),
        ),
        migrations.AddField(
            model_name='eficaz_prediction',
            name='result',
            field=models.ForeignKey(to='annotation.Eficaz_result'),
        ),
        migrations.AddField(
            model_name='ec_reaction',
            name='ec',
            field=models.ForeignKey(to='annotation.EC'),
        ),
        migrations.AddField(
            model_name='ec_reaction',
            name='reaction',
            field=models.ForeignKey(to='annotation.Reaction'),
        ),
        migrations.AddField(
            model_name='ec_reaction',
            name='source',
            field=models.ForeignKey(blank=True, to='annotation.Source', null=True),
        ),
        migrations.AddField(
            model_name='ec',
            name='enzymes_ec',
            field=models.ManyToManyField(to='annotation.Enzyme', through='annotation.Catalyst_ec'),
        ),
        migrations.AddField(
            model_name='ec',
            name='go_terms',
            field=models.ManyToManyField(to='annotation.GO', null=True, through='annotation.GO2EC', blank=True),
        ),
        migrations.AddField(
            model_name='ec',
            name='reactions',
            field=models.ManyToManyField(to='annotation.Reaction', through='annotation.EC_Reaction'),
        ),
        migrations.AddField(
            model_name='ec',
            name='source',
            field=models.ForeignKey(blank=True, to='annotation.Source', null=True),
        ),
        migrations.AddField(
            model_name='compartment',
            name='source',
            field=models.ForeignKey(blank=True, to='annotation.Source', null=True),
        ),
        migrations.AddField(
            model_name='combfunc_result',
            name='gene',
            field=models.ForeignKey(to='annotation.Gene'),
        ),
        migrations.AddField(
            model_name='combfunc_result',
            name='go_term',
            field=models.ForeignKey(to='annotation.GO'),
        ),
        migrations.AddField(
            model_name='combfunc_prediction',
            name='gene',
            field=models.ForeignKey(to='annotation.Gene'),
        ),
        migrations.AddField(
            model_name='combfunc_prediction',
            name='go',
            field=models.ForeignKey(to='annotation.GO'),
        ),
        migrations.AddField(
            model_name='combfunc_prediction',
            name='reaction',
            field=models.ForeignKey(to='annotation.Reaction'),
        ),
        migrations.AddField(
            model_name='combfunc_prediction',
            name='result',
            field=models.ForeignKey(to='annotation.Combfunc_result'),
        ),
        migrations.AddField(
            model_name='cogzyme_prediction',
            name='reaction',
            field=models.ForeignKey(to='annotation.Reaction'),
        ),
        migrations.AddField(
            model_name='catalyst_go',
            name='enzyme',
            field=models.ForeignKey(to='annotation.Enzyme'),
        ),
        migrations.AddField(
            model_name='catalyst_go',
            name='evidence',
            field=models.ForeignKey(to='annotation.FFPred'),
        ),
        migrations.AddField(
            model_name='catalyst_go',
            name='go_term',
            field=models.ForeignKey(to='annotation.GO'),
        ),
        migrations.AddField(
            model_name='catalyst_ec',
            name='ec',
            field=models.ForeignKey(to='annotation.EC'),
        ),
        migrations.AddField(
            model_name='catalyst_ec',
            name='enzyme',
            field=models.ForeignKey(to='annotation.Enzyme'),
        ),
        migrations.AddField(
            model_name='catalyst_ec',
            name='evidence',
            field=models.ForeignKey(to='annotation.NCBI'),
        ),
        migrations.AddField(
            model_name='catalyst',
            name='enzyme',
            field=models.ForeignKey(to='annotation.Enzyme'),
        ),
        migrations.AddField(
            model_name='catalyst',
            name='evidence',
            field=models.ForeignKey(to='annotation.Evidence'),
        ),
        migrations.AddField(
            model_name='catalyst',
            name='reaction',
            field=models.ForeignKey(to='annotation.Reaction'),
        ),
    ]
